// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


//import frc.robot.commands.*;
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
//import edu.wpi.first.wpilibj.motorcontrol.VictorSP;

import com.ctre.phoenix.motorcontrol.VictorSPXControlMode;
//import edu.wpi.first.wpilibj.motorcontrol.Victor;
import com.ctre.phoenix.motorcontrol.can.*;
//import com.
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveSubsystem extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private VictorSPX left1;
private VictorSPX right1;
private DifferentialDrive differentialDrive1;
private VictorSPX left2;
private VictorSPX right2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public DriveSubsystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
left1 = new VictorSPX(Constants.DriveConstants.LeftFront);
 //addChild("Left1",left1);
 left1.setInverted(false);

right1 = new VictorSPX(Constants.DriveConstants.RightFront);
 //addChild("Right1",right1);
 right1.setInverted(true);

differentialDrive1 = new DifferentialDrive(this::leftset, this::rightset);
 addChild("Differential Drive 1",differentialDrive1);
 differentialDrive1.setSafetyEnabled(true);
differentialDrive1.setExpiration(0.1);
differentialDrive1.setMaxOutput(1.0);


left2 = new VictorSPX(Constants.DriveConstants.LeftRear);
 //addChild("Left2",left2);
 left2.follow(left1);
left2.setInverted(false);

right2 = new VictorSPX(Constants.DriveConstants.RightRear);
 //addChild("Right2",right2);
 right2.follow(right1);
right2.setInverted(true);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }
    public void leftset(double input){
        left1.set(VictorSPXControlMode.PercentOutput, input);
    }
    public void rightset(double input){
        right1.set(VictorSPXControlMode.PercentOutput, input);
    }
    public void drive(double left, double right){
        differentialDrive1.tankDrive(left, right);
    }
    public void stop(){
        differentialDrive1.tankDrive(0, 0);
    } 
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

